### ISSUE TITLE
How can you load data from a vector 

### ISSUE THREAD

**Issue by jdkealy** [hswick/jutsu.ai#17]
Hi! 

Awesome library. I'm trying to test out some different data sets and I'd like to just load a data set from memory or pull it from a different database and evaluate it in the repl without converting it to a CSV first. Is this possible?

**Comment by hswick** [comment]
Unfortunately, I don't think such a feature is supported by deeplearning4j's datavec library. I tried implementing such a feature before, but there was formatting problems as dl4j's RecordReader is doing some pretty specific stuff. It has been a while since I've looked at the datavec API so there might be some new features to help out with this, you can take a look here https://github.com/deeplearning4j/deeplearning4j/tree/master/datavec.

If you come across anything useful feel to submit a PR!

**Comment by agibsonccc** [comment]
Can you clarify what you mean by "vector"? Data has to start from somewhere. We can pull things from arrow, numpy, or you can create an NDArrayWritable which wraps an ndarray. There are tons of ways to do it.

**Comment by hswick** [comment]
Oh hi @agibsonccc nice to see you here. I believe he means plain clojure vectors. Say a vector of vectors of floats. Seems like creating a function to convert clojure vector -> ndarray -> NDArrayWritable would be the best path.

**Comment by agibsonccc** [comment]
That would be your best bet then yes.
